---
title: "Case 2 Part 1"
author: "Sonia Xu"
date: "September 29, 2017"
output: html_document
---

<!--Week 1: Case study introduced in detail in the Wed lecture including questions from the students, and some relevant background on how the data were collected, the scientific focus, common ways to analyze the data, etc.  Students are expected to download the data, conduct exploratory/descriptive analyses of the data, clean the data (as needed) and outline several possible approaches for analyzing the data to address the scientific goals of the study by the next week’s lecture (at which point a write-up describing the results from the initial analyses and the different potential approaches to analysis) is due.  These interim reports will be graded, and should include a short description of the roles of each of the “authors” (team members) in the work.  -->


<!---
CASE STUDY 2: 

BACKGROUND: Study of time to critical neurological assessment for patients with stroke-like symptoms who are admitted to the emergency room.  A possible predictor is number of major stroke symptoms reported, ranging from 0 to 4.  Treatment for acute stroke includes thrombolytic therapy, which can potentially improve neurological functioning for ischemic stroke patients if administered soon after symptom onset (within 3 hours).  Since treating patients quickly is critically important for their long-term prognosis, minimizing the times from symptom onset to emergency room (ED) arrival, from ED arrival to diagnosis, and from diagnosis to treatment is of paramount concern.

INTEREST: Factors predictive of the time to critical neurological assessment following admission to the ED for n=335 patients with mild to moderate motor impairment.  The goal of the analysis is to perform inferences on the impact of clinical presentation, gender and race on time to neurological assessment.  Clinical presentation is measured as a count of reported major stroke symptoms, including headache, loss of motor skills or weakness, trouble talking or understanding, and vision problems.

Variable key: 
nctdel = min of neurologist time to assessment & CT scan from arrival at ER
fail = 1 if got neurologist/CT scan & 0 otherwise
male = 1 if male, 0=female
black = 1 if black, 0=not black 
hisp = 1 if hispanic, 0=not hispanic
sn1 = 0/1 indicator 1 main symptom
sn2 = 0/1 indicator 2 main symptoms
sn3 = 0/1 indicator 3 main symptoms 
all4 = 0/1 indicator all 4 main symptoms
--->

#load libraries
```{r}
library(dplyr)
library(magrittr)
```

#Read in Dataset
```{r}
kelly <- read.table("kellydat.txt", header = T)
```

#Cleaning the Data
#redo the count of symptoms
```{r}
kelly <- kelly %>% mutate(count_sn = sn1 + sn2*2 + sn3*3 + all4*4) %>% select(-c(sn1, sn2, sn3, all4))

```

#Exploratory Data Analysis
-talk about bias
  -look for racial and gender bias
  
-compare the differences between who was rejected and who wasn't (fail)

```{r}

hist(kelly$count_sn,breaks=100)

```

#Possible Approaches to the Data
```{r}

```

